name: "TODO to Issue"
description: "Converts IDE TODO comments to GitHub issues"
author: "Alastair Mooney"
runs:
  using: "composite"
  steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ inputs.owner }}
        repositories: ${{ inputs.TARGET_REPO }}

    - name: Change todo to issue
      id: todo-to-issue
      uses: docker://reg.dev.krd/todo-to-issue-action/todo-to-issue:dev
      env:
        REPO: ${{ inputs.REPO }}
        TARGET_REPO: ${{ inputs.TARGET_REPO }}
        BEFORE: ${{ inputs.BEFORE }}
        COMMITS: ${{ inputs.COMMITS }}
        DIFF_URL: ${{ inputs.DIFF_URL }}
        SHA: ${{ inputs.SHA }}
        TOKEN: ${{ inputs.TOKEN }}
        LABEL: ${{ inputs.LABEL }}
        COMMENT_MARKER: ${{ inputs.COMMENT_MARKER }}
        CLOSE_ISSUES: ${{ inputs.CLOSE_ISSUES }}
        AUTO_P: ${{ inputs.AUTO_P }}
        PROJECTS_SECRET: ${{ inputs.PROJECTS_SECRET }}
        USER_PROJECTS: ${{ inputs.USER_PROJECTS }}
        ORG_PROJECTS: ${{ inputs.ORG_PROJECTS }}
        IGNORE: ${{ inputs.IGNORE }}
        AUTO_ASSIGN: ${{ inputs.AUTO_ASSIGN }}
        ACTOR: ${{ inputs.ACTOR }}
        ISSUE_TEMPLATE: ${{ inputs.ISSUE_TEMPLATE }}
        IDENTIFIERS: ${{ inputs.IDENTIFIERS }}
        GITHUB_URL: ${{ inputs.GITHUB_URL }}
        ESCAPE: ${{ inputs.ESCAPE }}
branding:
  icon: "check-square"
  color: "orange"
inputs:
  owner:
    description: "Owner of the repository if it is not the current one"
    default: ${{ github.repository_owner }}
    required: false
  app-id:
    description: "The id of the GitHub App"
    required: true
  private-key:
    description: "The private key of the GitHub App"
    required: true
  REPO:
    description: "The path to the repository where the action will be used, e.g. 'alstr/my-repo' (automatically set)"
    required: false
    default: "${{ github.repository }}"
  TARGET_REPO:
    description: "The path to the GitOps repostiory, e.g 'ditkrg/pilgrimage-gitops"
    required: true
  BEFORE:
    description: "The SHA of the last pushed commit (automatically set)"
    required: false
    default: "${{ github.event.before || github.base_ref }}"
  COMMITS:
    description: "An array of commit objects describing the pushed commits"
    required: false
    default: "${{ github.event.commits }}"
  DIFF_URL:
    description: "The URL to use to get the diff (automatically set)"
    required: false
    default: "${{ github.event.pull_request.diff_url }}"
  SHA:
    description: "The SHA of the latest commit (automatically set)"
    required: false
    default: "${{ github.sha }}"
  TOKEN:
    description: "The GitHub access token to allow us to retrieve, create and update issues (automatically set)"
    required: false
    default: ${{ github.token }}
  LABEL:
    description: "The label that will be used to identify TODO comments (deprecated)"
    required: false
  COMMENT_MARKER:
    description: "The marker used to signify a line comment in your code (deprecated)"
    required: false
  CLOSE_ISSUES:
    description: "Optional input that specifies whether to attempt to close an issue when a TODO is removed"
    required: false
    default: true
  AUTO_P:
    description: "For multiline TODOs, format each line as a new paragraph when creating the issue"
    required: false
    default: true
  PROJECTS_SECRET:
    description: "Encrypted secret corresponding to your personal access token (do not enter the actual secret)"
    required: false
  USER_PROJECTS:
    description: "Default user projects"
    required: false
  ORG_PROJECTS:
    description: "Default organisation projects"
    required: false
  IGNORE:
    description: "A collection of comma-delimited regular expression that matches files that should be ignored when searching for TODOs"
    required: false
  AUTO_ASSIGN:
    description: "Automatically assign new issues to the user who triggered the action"
    required: false
    default: false
  ACTOR:
    description: "The username of the person who triggered the action"
    required: false
    default: "${{ github.actor }}"
  ISSUE_TEMPLATE:
    description: "The template used to format new issues"
    required: false
  IDENTIFIERS:
    description: "Dictionary of custom identifiers"
    required: false
  GITHUB_URL:
    description: "Base url of GitHub API"
    required: false
    default: ${{ github.api_url }}
  ESCAPE:
    description: "Escape all special Markdown characters"
    required: false
    default: true
